name: Build and Release Binaries

# Trigger nur bei Tags, die mit 'v' beginnen
on:
  push:
    tags:
      - "v*"

# Hier kannst du den Namen für die Artefakte konfigurieren
env:
  ARTIFACT_NAME: my_rust_binary # Ändere dies zu deinem gewünschten Namen

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      # Definiert die Betriebssysteme, auf denen gebaut werden soll
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # Du kannst hier deine bevorzugte Python-Version angeben

      - name: Install maturin
        run: pip install maturin

      - name: Build wheels
        # Baut das Rust-Projekt als Python-Wheel
        # --release sorgt für einen optimierten Build
        # --out dist legt die fertigen Dateien in den Ordner "dist"
        run: maturin build --release --out dist

      - name: Upload artifacts
        # Lädt die gebauten Binaries als Artefakte hoch
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}-${{ matrix.os }}
          path: dist/
